//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoskorSecurityTransport.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Destination
    {
        [Required]
        [Display(Name = "Destination Id")]
        public int DestinationID { get; set; }

        [Required]
        [Display(Name = "Destination Name")]
        public string DestinationName { get; set; }

        [Required]
        [Display(Name = "Status")]
        public string Status { get; set; }
    }
}
