//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoskorSecurityTransport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operator
    {
        public int OperatorID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string CompanyNumber { get; set; }
        public string OperatorRole { get; set; }
        public string Department { get; set; }
        public string Status { get; set; }
    }
}
