//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoskorSecurityTransport.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reason
    {
        [Required]
        [Display(Name = "Reason Id")]
        public int ReasonID { get; set; }

        [Required]
        [Display(Name = "Reason Name")]
        public string ReasonName { get; set; }

        [Required]
        [Display(Name = "Status")]
        public string Status { get; set; }
    }
}
