//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoskorSecurityTransport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int TripID { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public string StartingPoint { get; set; }
        public string Passenger1 { get; set; }
        public string CompanyNumber1 { get; set; }
        public string Destination1 { get; set; }
        public string Passenger2 { get; set; }
        public string CompanyNumber2 { get; set; }
        public string Destination2 { get; set; }
        public string Passenger3 { get; set; }
        public string CompanyNumber3 { get; set; }
        public string Destination3 { get; set; }
        public string Passenger4 { get; set; }
        public string CompanyNumber4 { get; set; }
        public string Destination4 { get; set; }
        public string Department1 { get; set; }
        public string Supervisor1 { get; set; }
        public string Reason { get; set; }
        public string Driver { get; set; }
        public string Vehicle { get; set; }
        public Nullable<int> KMOut { get; set; }
        public Nullable<int> KMIn { get; set; }
        public Nullable<int> TotalKMs { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        public Nullable<System.TimeSpan> TimeIn { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> SDateTime { get; set; }
        public string Capturer { get; set; }
        public string Supervisor2 { get; set; }
        public string Supervisor3 { get; set; }
        public string Supervisor4 { get; set; }
        public string Department2 { get; set; }
        public string Department3 { get; set; }
        public string Department4 { get; set; }
        public Nullable<int> noOfPassengers { get; set; }
    }
}
